### PR TITLE
Turn on security checker and do composer update

### PR DESCRIPTION
**Pull request by relaxnow**
At Ibuildings we would like to take a more proactive role at monitoring and alerting for security updates of the software we create and deliver to customers.

As part of this, for this project we'd like to:
- Upgrade to the latest patch level of Symfony 2.7
- Upgrade to the latest patch level of Zend Framework 1
- Upgrade to the latest minor level of simplesamlphp/simplesamlphp
- Turn on the security checker and make it fail pull requests.

Unfortunately I had to do a full composer update as Composer got lost with all the interdependencies of EB, SSP, SAML2 and XMLSecLibs.
Please see the commit for a full overview of all upgraded packages.

Also we'd like to turn on nightly builds ( https://docs.travis-ci.com/user/cron-jobs/ ), though I think I can request this from Travis.

### CODE REVIEW

**Comment by thijskh** [comment]
This would solve #213.

**Comment by arothuis** [comment]
Upgrading our dependencies to more secure, less buggy versions seems like a plan to me.

**Comment by DRvanR** [comment]
Certainly a good plan! A rebase on master should be done though as more tests have been added/enabled to see if everything still works as intended, especially with the update of SimpleSamlPHP. 

After rebase and succesful build a :+1: :x: :100:  from me!

**Comment by arothuis** [comment]
Upgrading Symfony from 2.7.4 to 2.7.6 removes the `ClockMock` we're using to test our `ExecutionTimeTracker` which uses Symfony's `Stopwatch`.

Therefore, before we can update our Symfony version we should create our own mockable Stopwatch implementation. This would also be an opportunity to correct our [occasionally failing tests](https://www.pivotaltracker.com/story/show/131718959) regarding the `ExecutionTimeTracker`.

**Comment by DRvanR** [comment]
Implementing a custom Stopwatch is trivial and at the same time provides the opportunity to create a TimeProvider object that ensures all time/timing related features can be tested properly.

**Comment by relaxnow** [comment]
@DRvanR 
> A rebase on master should be done though as more tests have been added/enabled to see if everything still works as intended, especially with the update of SimpleSamlPHP.

This branch is based on the most recent master?

**Comment by DRvanR** [comment]
yes, I rebased it - hence the failing build and the note from @arothuis  😉

**Comment by relaxnow** [comment]
@DRvanR anything I can do to help this along?

**Comment by arothuis** [comment]
@relaxnow, the build should succeed, so we could start by implementing a custom `Stopwatch` and `TimeProvider`. That way, we don't need Symfony's `ClockMock` to test our `ExecutionTimeTracker` anymore.

**Comment by nicwortel** [comment]
See #328

**Comment by nicwortel** [comment]
Closing in favor of #398

**Pull request closed without merging**
