### PR TITLE
Add symfony support to makeRelease, exclude theme from release

### PR DESCRIPTION
**Pull request by DRvanR**

### CODE REVIEW

**Comment by DRvanR** [comment]
@thijskh @arothuis questions, remarks?

**Comment by thijskh** [comment]
I'm wondering if there aren't cases where having the theme files available for a local update would be convenient.

**Comment by DRvanR** [comment]
I don't have any issue with keeping them. However the theme is dumped and the dumped files are in the source tree as well, editing the source tree within a release to me makes more sense than editing the theme and then dumping it to overwrite the actual files being used. Thoughts?

**Comment by thijskh** [comment]
Because of minification I think editing something like css is then a bit harder..

**Comment by DRvanR** [comment]
Keeping themes dir now, any other thoughts/objections/comments?

**Comment by thijskh** [comment]
Fine!

**Pull request merged**
