### PR TITLE
PHP 7.2 compatibility changes

### PR DESCRIPTION
**Pull request by MKodde**
This PR updates the EngineBlock codebase to a bare minimum to get PHP 7.2 support. We can and will drop PHP 5.6 support in this release.

In order to test this branch, you will need a OpenConext-deploy instance that also has the PHP 7.2 php-fpm pool available, configured and running for use with EB and EB API.

:warning: Be advised, if you are coming from an older Engine version (pre 5.12) then please upgrade to 5.13 first. Or at least manually run the database migrations (do not forget to push manage metadata to EB afterward. For doing that, it's advised to have an active Manage session during installation)

**Installation**
For installation of the PHP 7.2 requirements deploy this branch: https://github.com/OpenConext/OpenConext-deploy/pull/233

For OpenConext dev vm users:
`ENV=dev vagrant provision`

To configure Apache to use the PHP 7.2 php-fpm pool. SSH into your OpenConext-deploy `apps` machine:

1. The EngineBlock php-fpm pool config needs to be set up
1. `$ sudo cp /etc/opt/remi/php72/php-fpm.d/profile-pool-72.conf /etc/opt/remi/php72/php-fpm.d/engine-pool-72.conf`
1. Change profile references to engine
1. `$ sudo sed -i 's/profile/engine/g' engine-pool-72.conf`
1. `$ sudo vi /etc/httpd/conf.d/engine.conf`
1. Update the `ProxyPassMatch` line (l 33). `unix:/var/run/php-fpm/engine-pool.sock`  to: `unix:/var/run/php-fpm/engine-pool-72.sock`
1. Repeat these steps for `engine-api.conf`
1. We need APC backwards compatibility features
1. `$ sudo yum install php72-php-pecl-apcu-bc` // can be fixed with doctrine upgrade?
1. Clear the application caches: `$ php72 /opt/openconext/OpenConext-engineblock/app/console ca:cl --env=dev`. If need be, adjust the `env` argument to your environment of choice.
1. Verify you are using a PHP 7.2 compatible app_dev.php in your EB installation. Use the dist file if need be.
1. Restart apache: `sudo systemctl restart httpd`
1. Restart php-fpm: `sudo systemctl restart php72-php-fpm`

### CODE REVIEW

**Comment by thijskh** [comment]
The use of `Throwable` would imply to drop support for PHP 5.6?

**Comment by thijskh** [comment]
We've decided to go to PHP 7.2 without looking back

**Comment by MKodde** [comment]
Yes, and for the record. We are not updating to a more recent PHP version, to prevent major updates to the Symfony/Doctrine installation. When we are going to update to a modern version of Symfony, we should also be able to bump to PHP 7.3 or even 7.4. Which, hopefully, by then is matured to an extent that we feel comfortable about, running on our platform.

**Comment by MKodde** [comment]
I've updated the .travis.yml config
- Dropped the PHP 5.6 builds
- Removed 5.6 specific config settings from the `before_scripts` section

Which is now warranted as we no longer aim to be backward compatible for the first 7.2 release

**Comment by MKodde** [comment]
The functional test breaks on the issue that is resolved in #756

**Comment by MKodde** [comment]
@pablothedude the test is not broken. The template rendered in the error producing Behat test contained the reference to the SP fields that where removed in #755

What would you like to see changed here?

**Comment by pablothedude** [comment]
But that didn't result in a broken build, so why does it fail now and not before? As you can see master is also green.

If you can make this build green I'm happy.

**Comment by MKodde** [comment]
As a fix for now, the incriminating tests have been marked with the @WIP annotation. These tests only fail on Travis. Where the test repository is unable to find the SP used in the test. A ticket was opened to fix this permanently.

https://www.pivotaltracker.com/story/show/168698275

**Pull request merged**
