### PR TITLE
Log the Engine SSO endpoint used

### PR DESCRIPTION
**Pull request by MKodde**
After a successfull login, log the sso endpoint used during authentication. This is available on the _request var present on the
LogLogin command.

https://www.pivotaltracker.com/story/show/175904919

### CODE REVIEW

**Comment by MKodde** [comment]
Sir, quartermaster @quartje, does this meet your requirements, sir?

**Comment by MKodde** [comment]
What's being logged is:

```
Mar 29 15:41:12 apps.vm.openconext.org EBAUTH[1307]: {"channel":"authentication","level":"INFO","message":"login granted","context":{"login_stamp":"2021-03-29T15:41:12.442692+02:00","user_id":"urn:collab:person:example.com:asdfasdf","sp_entity_id":"https://profile.vm.openconext.org/authentication/metadata","idp_entity_id":"http://mock-idp","key_id":null,"proxied_sp_entity_ids":[],"workflow_state":"prodaccepted","original_name_id":"urn:collab:person:example.com:asdfasdf","authncontextclassref":"urn:oasis:names:tc:SAML:2.0:ac:classes:Password","engine_sso_endpoint_used":"https://engine.vm.openconext.org/authentication/idp/single-sign-on"},"extra":{"session_id":"7ruj1vn6cg8hrdeij5bl6teves","request_id":"6061d8f7de05a"}}
```

**Comment by quartje** [comment]
When using the md5 hash of the IdP in the path like this:
https://engine.vm.openconext.org/authentication/idp/single-sign-on/key:xxxx/md5hashoftheidp
would that be explicitly logged by this change?

**Comment by MKodde** [comment]
Do you hint at the unsolicited SSO option? If that's the case, no the original destination of the SSO AuthNRequest is lost. But the request is flagged as being unsolicited. So I would be able to reconstruct the idp hash and the url-encoded sp EntityId.

**Comment by thijskh** [comment]
No, I think Bart refers to the different ways you can start a regular Authentication Request on EB.

An SP can call e.g.:
https://engine.vm.openconext.org/authentication/idp/single-sign-on
https://engine.vm.openconext.org/authentication/idp/single-sign-on/key:20210330
https://engine.vm.openconext.org/authentication/idp/single-sign-on/234353ee1e96b99f9bb5f488a235982b
https://engine.vm.openconext.org/authentication/idp/single-sign-on/key:20210330/234353ee1e96b99f9bb5f488a235982b

If one SP uses the first and another SP uses the last, will this be visible in different logged strings?

**Comment by MKodde** [comment]
Ah, yes forgot this is is possible too, I will check if that gets logged correctly. I do think this is already the case. The unsolicited sso was the strange :duck: when it comes to storing the incoming authn request from the 'SP'.

**Comment by MKodde** [comment]
Confirmed, the IdP hash in the sso uri is also logged. As proved by this: (same would apply when specifying a key)

```
Mar 30 11:59:01 apps.vm.openconext.org EBAUTH[1307]: {"channel":"authentication","level":"INFO","message":"login granted","context":{"login_stamp":"2021-03-30T11:59:01.681569+02:00","user_id":"urn:collab:person:example.com:rftgyj","sp_entity_id":"https://profile.vm.openconext.org/authentication/metadata","idp_entity_id":"http://mock-idp","key_id":null,"proxied_sp_entity_ids":[],"workflow_state":"prodaccepted","original_name_id":"urn:collab:person:example.com:rftgyj","authncontextclassref":"urn:oasis:names:tc:SAML:2.0:ac:classes:Password","engine_sso_endpoint_used":"https://engine.vm.openconext.org/authentication/idp/single-sign-on/234353ee1e96b99f9fa5f488a235982b"},"extra":{"session_id":"9d9bghurbqfpe5kj3gce3sgkfh","request_id":"6062f64daec8b"}}
```

**Pull request merged**
