### PR TITLE
Convert NotFoundHttpExceptions to proper 404 pages

### PR DESCRIPTION
**Pull request by DRvanR**
See https://www.pivotaltracker.com/story/show/107472822

### CODE REVIEW

**Comment by DRvanR** [comment]
@rjkip @arothuis

**Comment by rjkip** [comment]
This not only affects authentication, but also API. IMO it's about the integration of Symfony and the old framework. What about putting it in the compatibility layer?

I know the ticket is about Symfony's HTTP exceptions, but what about other exceptions? The old EB has a nice error page when exceptional conditions occur:

https://engine.surfconext.nl/authentication/idp/process-wayf
vs
https://engine.vm.openconext.org/authentication/idp/process-wayf

**Comment by DRvanR** [comment]
Api is already covered by the use of `ApiHttpException` (furthermore, this is not limited to occurrences only from within the AuthenticationBundle (it's an eventlistener). 

All known and identified exceptions that were caught in controllers are handled in the same way by Symfony. What I did miss is that the old dispatcher has a "catch all" exception handling that allowed graceful recovery.
Will add that to this PR

**Comment by rjkip** [comment]
> furthermore, this is not limited to occurrences only from within the AuthenticationBundle (it's an eventlistener)

Point in case. Feels to me the AuthenticationBundle is a specific part of the application that now handles not found pages for the entire application.

**Comment by DRvanR** [comment]
Fair enough, will relocate it

**Comment by DRvanR** [comment]
@rjkip :bell:

**Comment by rjkip** [comment]
:sparkles::ship::sparkles:

Awe-struck.

**Comment by arothuis** [comment]
:+1:

**Pull request merged**
