### PR TITLE
Allow enforcing requesterid on trusted proxy

### PR DESCRIPTION
**Pull request by tvdijen**
As per mailinglist discussion:
https://groups.google.com/forum/#!topic/openconext/riXK5xjacIw

Default (current) behaviour:
Trusted proxy sets no requesterId > all attributes are released

New behaviour when 'requesterid_required' is true:
Trusted proxy sets no requesterid > Raise unknown service exception

### CODE REVIEW

**Comment by jorissteyn** [comment]
I believe it would be fitting to add a `@SuppressWarnings(PHPMD.TooManyFields)` to `OpenConext\EngineBlock\Metadata\Entity\ServiceProvider` - don't feel bad about it :)

**Comment by tvdijen** [comment]
Done!

**Comment by tvdijen** [comment]
Rebased + documented.. Let me know if this suffices.

**Comment by MKodde** [comment]
Thanks a lot @tvdijen! I'm going to merge this into master.

Keeping the `CHANGELOG.md` is a new thing, as of EB 5.9 we want to introduce this into our development routine. This greatly reduced the research work when whipping up a release and writing the release notes then.

**Pull request merged**
