### PR TITLE
Merging master into 5.x-dev

### PR DESCRIPTION
**Pull request by DRvanR**

### CODE REVIEW

**Comment by DRvanR** [comment]
@thijskh @quartje 

This PR should make `5.x-dev` mergeable to `master`. Do note that these are changes already in `master` going into `5.x-dev`, with the exception of [the line adding support for the Ldap port][sf-ldap] configuration value within Symfony.

After merging this, `5.x-dev` could be merged into master.

---

#### The road to 5.0.0

##### What is already done?

* As said, with this PR `5.x-dev` could be merged into `master`
* The favicon as updated in `master` has been added to `5.x-dev` as well
* The README.md and UPGRADING.md have been updated to reflect the `5.x-dev` changes.

##### What should still be done?

* Merge this branch
* See if [any changes in `develop` not yet in `5.x-dev`][dev-5.x] should be merged. If so, make a pull request accommodating those changes against `5.x-dev`

##### Recommendation

After the point above, I would like to suggest the following course of action:

1. Remove the `develop` branch
2. Remove all [branches beginning with `junk`][junk]
3. (optional) Release one lastest 4.8.0 version of EB which should reflect the current state of `master`
4. Formally note (in the wiki?) that EngineBlock 4.8.0 is the last minor range of the 4.x version range. It should only receive patches in case of reported security vulnerabilities that require fixes.
5. Fork a 4.8 branch from master (in case of a 4.8.0 release, otherwise a [4.7 branch][4.7] already exists based on the current master) for patch releases should they be needed for X amount of time.
6. Merge `5.x-dev` to `master`
7. Adopt the [github flow][gf] - in essence: feature brances, PRs to master, master must always be deployable. Could be documented in the Wiki or a DEVELOPMENT.md. If so, mark the `master` branch as [protected branch][pb1] in github (see also [here][2]) - might be a good idea anyways.
8. Tag `5.0.0`, :tada: 
9. Mark 5.0 as current stable release (wiki)

This cleans up a lot of branches, formalizes current stable and previous stable, adopts a branching model and enforces that through protected branches. Also, gives a 5.0.0 release :wink: 

I would be able to do the above tomorrow morning, after that first possible would be somewhere this weekend, please let me know if you want me to do this.

[sf-ldap]: https://github.com/OpenConext/OpenConext-engineblock/pull/319/files#diff-f728a235666a96c7488ac36021c80be5R96
[dev-5.x]: https://github.com/OpenConext/OpenConext-engineblock/compare/5.x-dev...develop?expand=1
[junk]: https://github.com/OpenConext/OpenConext-engineblock/branches/all?utf8=%E2%9C%93&query=junk
[4.7]: https://github.com/OpenConext/OpenConext-engineblock/tree/4.7
[gf]: http://scottchacon.com/2011/08/31/github-flow.html
[pb1]: https://help.github.com/articles/about-protected-branches/
[pb2]: https://help.github.com/articles/configuring-protected-branches/

**Comment by thijskh** [comment]
Agree with the steps up to and including "what should still be done" (there's definitely some minor stuff in `develop` that we want to merge).

I would skip steps 3…5 as I foresee a significant chance that no users will need a final release of 4.8 or any followup releases. We can always do that if a concrete demand would surface.

Step 2 is definitely fine.

As you've heard we're planning some real world exposure of RC1 this week. Let's await that to see if anything else pops up that we'd really want to be part of 5.0.0.

**Comment by thijskh** [comment]
1, 7 are about github-flow. I can see the merits of that and think I'm in favour. However, I'd appreciate the input of e.g. @pmeulen, @relaxnow and maybe even @oharsta to see if there's consensus about that way of working.

**Comment by DRvanR** [comment]
So concluding:

- this can be merged
- a new PR from develop to 5.x-dev should be made
- all `junk` branches can be removed

After that 5.x-dev could be merged to master, and after say another week (2 week period total) 5.0.0 could be tagged if there are no more changes required (stemming from the 5.0.0-rc1 release). 

Aside from that a discussion on a formal branching strategy should take place. Ideally this would be concluded prior to tagging 5.0.0 (that could even wait a bit) since for instance [git flow][1] has a different release strategy than the proposed [github flow][2].

If this is correct I'll take care of the 3 actions listed and create an issue for the branching model discussion, @mentioning the people listed hoping to get a reaction :wink: 

[1]: http://nvie.com/posts/a-successful-git-branching-model/
[2]: http://scottchacon.com/2011/08/31/github-flow.html

**Comment by thijskh** [comment]
I've asked around and the people who are not on holiday prefer github-flow over git-flow. I think it's fine to just go for that.

**Pull request merged**
