### PR TITLE
Reverse name/displayName order

### PR DESCRIPTION
**Pull request by tvdijen**
DisplayName should have preference over the technical name

### CODE REVIEW

**Comment by tvdijen** [comment]
Ah crap, let me fix that

**Comment by tvdijen** [comment]
Fixed

**Comment by thijskh** [comment]
Don't think JS should be changed...

**Comment by tvdijen** [comment]
Well, that's what happens when I run npm install && grunt...
Changes to the file seem syntactical only, so I suspect npm installed a newer version of a dependency..

**Comment by thijskh** [comment]
Personally I'd prefer to not "git add" that change then. Keeps it more clean.

**Comment by tvdijen** [comment]
As you wish

**Pull request merged**
