### PR TITLE
Fix portugese translations

### PR DESCRIPTION
**Pull request by pablothedude**
The Portuguese translations needed to be implemented.

### CODE REVIEW

**Comment by pablothedude** [comment]
@domgon would you be so kind to validate the Portuguese translations?

Thanks in advance!

**Comment by domgon** [comment]
Hi,

I saw some translations for the messages below and I'm gonna make a sugestion.

```
'error_sfo_callout_unknown_title'
'error_sfo_callout_unknown_desc'
'error_sfo_callout_unmet_loa_title'
'error_sfo_callout_unmet_loa_desc'
'error_sfo_callout_user_cancelled_title'
'error_sfo_callout_user_cancelled_desc'
```
Sorry for the delay to answer your request.

Regards

**Comment by domgon** [comment]
Below, you can find the last messages added on the file `languages/messages.pt.php` with my suggestions for the Portuguese language

```
'error_sfo_callout_unknown_title' => 'Erro - falha por autenticação forte desconhecida',
'error_sfo_callout_unknown_desc' => 'O login com autenticação forte falhou e não sabemos exatamente qual o motivo. Tente aceder de novo ao serviço e efetuar uma nova autenticação. Se voltar a não funcionar, entre em contato com o suporte técnico da sua %organisationNoun%.',
'error_sfo_callout_unmet_loa_title' => 'Erro - não foi encontrado nenhum token adequado',
'error_sfo_callout_unmet_loa_desc' => 'Para continuar neste serviço, é necessário que o token registado tenho um determiando nível de confiança. Atualmente, você não tem um token registado, ou o nível de confiança do seu token é muito baixo. Veja o endereço abaixo para mais informações sobre o processo de registo.',
'error_sfo_callout_user_cancelled_title' => 'Erro - Carregamento cancelado',
'error_sfo_callout_user_cancelled_desc' => 'Você cancelou o processo de autenticação. Volte ao serviço se você pretender tentar de novo.',
```
If you need more help to translate or adapt something, you are welcome.

Regards

**Comment by domgon** [comment]
Hi, below my suggestion for the Portuguese messages for the file `languages/messages.pt.php`

I posted a previews comment with the translations but just after submit the message I notice an error, so I'm posting now the last version of the translations.

```
'error_sfo_callout_unknown_title' => 'Erro - falha por autenticação forte desconhecida',
'error_sfo_callout_unknown_desc' => 'O login com autenticação forte falhou e não sabemos exatamente qual o motivo. Tente aceder de novo ao serviço e efetuar uma nova autenticação. Se voltar a não funcionar, entre em contato com o suporte técnico da sua %organisationNoun%.',
'error_sfo_callout_unmet_loa_title' => 'Erro - não foi encontrado nenhum token adequado',
'error_sfo_callout_unmet_loa_desc' => 'Para continuar neste serviço, é necessário que o token registado tenho um determinado nível de confiança. Atualmente, você não tem um token registado, ou o nível de confiança do seu token é muito baixo. Veja o endereço abaixo para mais informações sobre o processo de registo.',
'error_sfo_callout_user_cancelled_title' => 'Erro - Carregamento cancelado',
'error_sfo_callout_user_cancelled_desc' => 'Você cancelou o processo de autenticação. Volte ao serviço se você pretender tentar de novo.',
```
If you need more help to translate other messages, you are welcome.

Regards,

**Comment by pablothedude** [comment]
Hi @domgon,

Thanks for your contribution. Muito obrigado!

Regards,

**Comment by domgon** [comment]
You are welcome @pablothedude !!!

**Pull request merged**
