### PR TITLE
Unminify CSS and JavaScript

### PR DESCRIPTION
**Pull request by tvdijen**
As discussed earlier in https://github.com/OpenConext/OpenConext-engineblock/pull/337 minifying CSS/JS doesn't add much because of GZip-compression, and makes the code pretty much unreadable.

### CODE REVIEW

**Comment by tvdijen** [comment]
Related: #339

**Comment by MKodde** [comment]
This pull request reminds me of [a discussion](https://stackoverflow.com/questions/16196358/why-do-people-minify-css-and-javascript-when-we-have-gzip) that I read about some time ago. TLDR: Yes, GZip compression is superior when it comes to serving smaller sized files, but minifying JS and CSS offers other important features:

* Removal of possible sensitive comments and doc-blocks
* Influences [search engine ranking](https://developers.google.com/speed/docs/insights/MinifyResources)
* Possibility to concatenate several css / js files (reduction in # requests) 

For production 'builds' I would suggest utilizing both techniques. When it comes to development, [source maps](http://blog.teamtreehouse.com/introduction-source-maps) might prove very useful in this situation. Luckily this feature is built into the [Grunt contrib module](https://github.com/gruntjs/grunt-contrib-uglify/blob/master/README.md#sourcemap) we use for minification.

**Comment by tvdijen** [comment]
>    Removal of possible sensitive comments and doc-blocks
Not really useful on open source projects
>    Influences search engine ranking
Not really useful in this case;  we always get redirected to EB by an SP
>    Possibility to concatenate several css / js files (reduction in # requests)
We can still do that without minifying

**Comment by MKodde** [comment]
>>    Removal of possible sensitive comments and doc-blocks

> Not really useful on open source projects

Why not? The original sources will keep their comments and doc-blocks. Contributors can still read and write comments while end users aren't.

>>    Influences search engine ranking

> Not really useful in this case;  we always get redirected to EB by an SP

I'm with you on this one.

>>    Possibility to concatenate several css / js files (reduction in # requests)

> We can still do that without minifying

True that.

**Pull request closed without merging**
