### PR TITLE
Added better descriptive information on the policy violation feedback

### PR DESCRIPTION
**Pull request by oharsta**
See https://www.pivotaltracker.com/story/show/123018241

### CODE REVIEW

**Comment by thijskh** [comment]
:+1:

**Comment by DRvanR** [comment]
Seem to miss the check whether or not the key `error_authorization_policy_violation_name` is set, this might lead to warnings. 
Furthermore, the theme has been changed, but the actual template (generated from the theme) that is used not :wink: See [here][1].

[1]: https://github.com/OpenConext/OpenConext-engineblock/#applying-a-new-theme

**Comment by oharsta** [comment]
Added `array_key_exists` for the user message, ran `grunt theme:material` and pushed changes.

**Comment by DRvanR** [comment]
:+1:

**Pull request merged**
