### PR TITLE
Remove attribute_aggregation_required metadata setting

### PR DESCRIPTION
**Pull request by pablothedude**
The attribute aggregator is now only queried when the metadata setting
coin:attribute_aggregation_required is set. This is simplified and
therefore an SP does not require this extra setting to be enabled
anymore.

### CODE REVIEW

**Comment by jorissteyn** [comment]
We ought to drop this line too: https://github.com/OpenConext/OpenConext-engineblock/blob/master/src/OpenConext/EngineBlock/Metadata/Entity/Assembler/JanusPushMetadataAssembler.php#L193

**Comment by pablothedude** [comment]
Thanks. I've removed these line too.

**Comment by pablothedude** [comment]
I've removed the paragraph as requested.

**Comment by pablothedude** [comment]
Your changes make perfectly sense to me

**Pull request merged**
