### PR TITLE
Bugfix: JS and CSS compilation

### PR DESCRIPTION
**Pull request by arothuis**
This fixes an issue where vendor prefixes in compiled css were removed and updates the minified JavaScript because of changes in the underlying compilation/minification algorithm.

### CODE REVIEW

**Comment by thijskh** [comment]
Alright, I can see that the webkit stuff is now back, good! Will ask affected developers to test.

**Comment by thijskh** [comment]
Confirmed that it fixes the problem for embedded browser.

**Comment by arothuis** [comment]
The build fails due to an unrelated issue, see: #394.

**Comment by arothuis** [comment]
Merging as the failing build is caused by Travis and not by code changes on our side.

**Pull request merged**
