### PR TITLE
Ensure focus styles match the styleboard

### PR DESCRIPTION
**Pull request by Badlapje**
replaces #951 which, due to my absence, is now in rebase hell

### CODE REVIEW

**Review by MKodde — COMMENTED** [review]
I love the new focus styles! They are way more subtle (which might be slightly less advantageous to the visually impaired?) Is the light blue border around the main CTA button (continue to idp) contrasty enough?

I noticed the tooltips do not function correctly on the consent page. See screenshot below. This might not be related to this PR. So feel free to fix this in another PR. 

Screenshot_2020-10-29 OpenConext - Do you give consent to share your information

This is how the Consent screen loads in my Firefox. The tooltip text is partially visible from the start.

**Comment by Badlapje** [comment]
> I love the new focus styles! They are way more subtle (which might be slightly less advantageous to the visually impaired?) Is the light blue border around the main CTA button (continue to idp) contrasty enough?

The contrast is good enough, whether it stands out enough despite checking the contrast box is another matter though.  We'll have to see that in user tests / feedback.

**Comment by Badlapje** [comment]
> I noticed the tooltips do not function correctly on the consent page. See screenshot below. This might not be related to this PR. So feel free to fix this in another PR.

Good one!  Fixed.

**Comment by MKodde** [comment]
Ah, and also please squash the fixup commits. Those do not have to be included in version history

**Pull request merged**
