### PR TITLE
Adding Portuguese language to EngineBlock

### PR DESCRIPTION
**Pull request by domgon**
the changes on this pull request are to add the Portuguese language as an option to be used after an installation from ansible

### CODE REVIEW

**Comment by MKodde** [comment]
Nice work again, I see that PHP-MD nags about the constructor of ServiceProvider.php having too many lines of code. Feel free to add a [warning suppression](https://phpmd.org/documentation/suppress-warnings.html) for this case. We will refactor it when picking up the aforementioned story.

**Comment by domgon** [comment]
Hi MKodde,
thanks for the support. 
Sorry for the errors and number of commits I performed earlier. I was making the changes directly from the github.
Regarding the suggestion of adding a [warning suppression](https://phpmd.org/documentation/suppress-warnings.html) am i doing it well?
Regards

**Comment by domgon** [comment]
Hi
I made the change you suggest to restrict a little bit more the suppression warning. I applied your recommendation "**@SuppressWarnings(PHPMD.ExcessiveMethodLength)**". Even with that suppression it still failing the tests.
Is it suppose to have success after adding the suppression? Did I need to make more changes?
Sorry, for my fragility at this point of development :) This kind of development don't look to be complex but, I don't have experience on this development methods.
I'm use to be an Oracle DBA. Our development are very simpler. Just bash scripts, SQL and PL/SQL  :D
Best regards

**Comment by MKodde** [comment]
I enjoy helping you, no problem at all! I can imagine that this is quite a different development experience from your DBA work you are used to.

You can see in the Travis build output what is holding back on a green build. The build [overview](https://travis-ci.org/OpenConext/OpenConext-engineblock/builds/514595767?utm_source=github_status&utm_medium=notification) states that the functional tests are not yet passing. And PHP MD is still complaining. 

May I suggest that I resolve these issues and that I try to describe the fixes in depth in the commit messages. This way you can learn from the solution and the PR will not become stale.

**Comment by MKodde** [comment]
A small report of the things I changed, as this is not really evident when reading the commit messages:

1. Fixed the MD warning. You placed it in the doc block of the test. Where it should have been placed in the doc block of the ServiceProvider constructor. 
2. There was a small typo in the ConsentControllerTest.
3. I squashed several commits into each other, making the git log history slightly cleaner. This is not always good practice to do, as it involves rewriting of the history, resulting in `git push --force-with-lease` actions that might result in issues in colleagues working copies.

**Comment by MKodde** [comment]
@thijskh, @pmeulen How do we want to go about adding this feature to EngineBlock? Is this something for the 5.10 release, or do we want to postpone this for a later release?

**Comment by pablothedude** [comment]
Hi @domgon , thanks for your effort.

I would like to inform you that I've moved your work in this PR into #841 were I did resolve some merge conflicts. I've also added some additional logic to be able to handle PT as language to the metadata and SFO features which were added in the meantime. So you should be able to use PT as supported language in the upcoming 6.2 release.

Feel free to open up a PR if you encounter something that needs to be addressed. Because we don't speak Portuguese and don't use PT as language ourselves you would likely be the one to encounter regressions in this functionality  first.

For now I'll close this PR in favour of #841.

**Pull request closed without merging**
