### PR TITLE
Add theme variable overrides

### PR DESCRIPTION
**Pull request by pablothedude**
The vars couldn't be overridden due to the loading order of sass files.
This should be fixed now.

### CODE REVIEW

**Comment by tvdijen** [comment]
Works like a charm!

**Comment by pablothedude** [comment]
I've merged the missed variable from #732 back into this branch so it could be fixed all at once.

**Comment by MKodde** [comment]
We should target this release at 5.11 and onward. The current target is master (5.13). Be sure to cherry-pick these changes to the appropriate branches when finishing this!

**Comment by pablothedude** [comment]
On `master` is currently 5.11. The upcoming 5.11 and 5.12 releases are currently only in `feature/sfo` and are not yet merged back. So I don't think any cherry picking will be needed.

**Pull request merged**
