### PR TITLE
Use release identifier as cache buster

### PR DESCRIPTION
**Pull request by jorissteyn**
The makeRelease.sh script replaces a placeholder in config.yml when
creating a tarball, setting the 'asset_version' parameter to the tag,
branch or commit hash used to create the release. This value is used
as cache buster in the html template.

See https://www.pivotaltracker.com/story/show/154839009

### CODE REVIEW

**Comment by thijskh** [comment]
So it's not the commit hash, but the tag (e.g. "5.5.2"), right?

**Comment by tvdijen** [comment]
Do I really have to set this manually for every install from source??

**Comment by thijskh** [comment]
No, `bin/makeRelease.sh` will set it so any tarball will come with the tag set to the right value.

**Comment by tvdijen** [comment]
That's why I ask... I never use the official tarballs but build from source

**Comment by thijskh** [comment]
If you do that then you already have to run commands post-checkout like ‘composer’, so you could add some command to it.

But strictly speaking you’re not required to do anything new, you’ll always get the value “dev” (retaining the old behaviour).

**Comment by tvdijen** [comment]
I don’t dev, I get #ASSET_VERSION# ...   shouldn’t this default to the .ini’s version setting?

**Comment by MKodde** [comment]
I'd like to join this discussion. @tvdijen, is using (or manually building) tarballs not an option? If it is not, we can try to meet in the middle. For example, using a more sensible default value for the asset version replacement token. 

I'm not aware of a version number in the `application.ini`, maybe I'm overlooking something here that could be taken advantage of. Please explain.

**Comment by tvdijen** [comment]
Tarballs are not really an option, because I have too many customizations to apply..
I always clone the release-tag and merge in all the customizations, regenerate theme assets, etc..

The version-number I was referring to:
https://github.com/OpenConext/OpenConext-deploy/blob/master/roles/engineblock/templates/engineblock.ini.j2#L2

**Comment by MKodde** [comment]
I will try to look into using this version number instead of the one used to build a release with. 

A limitation with the usage of the `engineblock.ini`'s `version` is that we'll/you'll have to update it every time a new release is installed (as I assume you do not reprovision eb-deploy for each release), otherwise cache busting will still fail.

**Comment by tvdijen** [comment]
I don't use eb-deploy at all, because unfortunately I can't use ansible here...
Anyway, I already change the version number in `engineblock.ini` as I was under the impression that it is already required to do so...

**Pull request merged**
