### PR TITLE
Feature: configurable metadata

### PR DESCRIPTION
**Pull request by tvdijen**

### CODE REVIEW

**Comment by MKodde** [comment]
Hi @tvdijen an interesting addition to the metadata. Your change-set is looking great! The tests need some tweaking. Some of the metadata test are somewhat treacherous. If you want to rubber duck, or need some input from my part, feel free to contact me on Slack.

**Comment by MKodde** [comment]
The issue with the translator mock expectations can be resolved by changing the index to:

```
        $translator = $this->createMock(TranslatorInterface::class);
        $translator->expects($this->at(0))
            ->method('trans')
            ->with('suite_name')
            ->willReturn('test-suite');
        $translator->expects($this->at(1))
            ->method('trans')
            ->with('metadata_organization_name')
            ->willReturn('configuredOrganizationName');
        $translator->expects($this->at(2))
            ->method('trans')
            ->with('metadata_organization_displayname')
            ->willReturn('configuredOrganizationDisplayName');
        $translator->expects($this->at(3))
            ->method('trans')
            ->with('metadata_organization_url')
            ->willReturn('configuredOrganizationUrl');
```

**Comment by tvdijen** [comment]
> But using %suiteName%, %supportUrl% and such does not, they are not interpolated.

That's strange because %suiteName% is being used all over the place in the translations-file...

**Comment by thijskh** [comment]
Yes, this works when the string ends up being output in Twig, which is usually the case, but not for metadata.

**Comment by tvdijen** [comment]
But the metadata is build based on a Twig template? What am I missing here? :/

**Comment by thijskh** [comment]
Maybe they should be passed through the trans filter for it to work?

**Comment by tvdijen** [comment]
Thanks, I hadn't had time to look into this!

**Review by thijskh — APPROVED** [review]
Tested, works fine

**Comment by tvdijen** [comment]
We have noticed that the same issue with %placeholders% also applies to the md:Organization elements in the metadata. Those need to be passed through the translator too, or you will end up with invalid metadata (Shibboleth for example chokes on `<md:OrganizationURL>%supportURL%</md:Organization>` because it's not a valid URL.

**Pull request merged**
